# Generated by Django 5.0.6 on 2024-06-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_rename_modalities_modalitie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalitie',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
